import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier";
import jsdoc from "eslint-plugin-jsdoc";

// Components are PascalCase by React convention and helpers are not, so this
// keeps the parameter and return rules on every plain function and off every
// component.
const HELPERS_ONLY = ["FunctionDeclaration[id.name=/^[a-z]/]"];

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  prettier,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
  ]),
  // Don't flag a variable destructured only to omit it from a `...rest` sibling
  // (the "object without property X" idiom, e.g. `const { status, ...rest } = obj`).
  // `^_`-prefixed names stay ignored too, matching the usual convention.
  {
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { ignoreRestSiblings: true, argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  // The Prisma client never leaves the server boundary. Application code
  // (app/, src/lib, components, …) must reach the database only through a
  // service in src/server/services — never by importing the client or the
  // `prisma` singleton directly. Enforced everywhere EXCEPT:
  //   - src/server/**  the boundary itself (db.ts + services live here)
  //   - test/**        Node-only specs that mock the singleton / build Prisma errors
  //   - prisma/**      the seed script, a server-side tool that needs the client
  {
    files: ["**/*.{ts,tsx,mts}"],
    ignores: ["src/server/**", "test/**", "prisma/**"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              // The generated client + the raw Prisma runtime. Model *types*
              // (generated/prisma-*/models, …/enums) are deliberately NOT banned —
              // DTOs map from them via `import type`. The glob spans every
              // per-provider output directory: one client is generated for each
              // supported engine, and both must stay behind the service layer.
              group: [
                "@prisma/client",
                "@prisma/client/*",
                "**/generated/prisma-*/client",
                "**/generated/prisma-*/client/*",
                "**/generated/prisma-*/internal",
                "**/generated/prisma-*/internal/*",
              ],
              message:
                "Don't import the Prisma client outside src/server/. Call a service from src/server/services/ instead (model types from generated/prisma-*/models are fine).",
            },
            {
              group: ["@/src/server/db", "**/src/server/db"],
              message:
                "The `prisma` singleton is server-only. Call a service from src/server/services/ instead of importing src/server/db.",
            },
          ],
        },
      ],
    },
  },
  // Documentation conventions, per docs/guides/comments.md. Presence and shape
  // are checkable; whether a line is worth its space stays with review.
  //
  // Components are excluded from the tag rules by selector: React requires them
  // to be PascalCase, and a component has one parameter - a props object whose
  // members are documented on the type - so demanding a @param here would ask
  // for a tag named after a destructuring pattern.
  {
    files: ["app/**/*.{ts,tsx}", "src/**/*.{ts,tsx}", "test/**/*.ts"],
    // shadcn/ui is regenerated by its CLI, so a convention applied there is lost
    // on the next `shadcn add` rather than maintained.
    ignores: ["src/shared/components/ui/**"],
    plugins: { jsdoc },
    settings: { jsdoc: { mode: "typescript" } },
    rules: {
      "jsdoc/require-jsdoc": [
        "error",
        {
          contexts: [
            "FunctionDeclaration",
            "ClassDeclaration",
            "TSTypeAliasDeclaration",
            "TSInterfaceDeclaration",
            // Module scope only. A local inside a function body has one scope,
            // no callers, and its definition beside it.
            "Program > VariableDeclaration",
            // Matched on the export rather than the declaration inside it: the
            // doc block attaches to the export, so targeting the declaration
            // reports every documented one as undocumented.
            "Program > ExportNamedDeclaration[declaration.type='VariableDeclaration']",
            "Program > ExportNamedDeclaration > TSTypeAliasDeclaration",
            "Program > ExportNamedDeclaration > TSInterfaceDeclaration",
            // Members of a declared type, which are its interface. Exported or
            // not, for the same reason a function carries a block wherever it
            // is declared: a block that appears only sometimes cannot be told
            // apart from one that was missed. Not every property signature
            // anywhere, though - a props object written inline in a component
            // signature is that component's parameter list, not a type.
            "TSTypeAliasDeclaration > TSTypeLiteral > TSPropertySignature",
            "TSInterfaceDeclaration > TSInterfaceBody > TSPropertySignature",
          ],
        },
      ],
      "jsdoc/require-description": "error",
      // A destructured parameter has no name, so the rule invents one - asking
      // for `@param root0` and a line per property, which restates the type.
      // Those members are documented on the type itself, which is required to
      // carry blocks too.
      "jsdoc/require-param": ["error", { checkDestructuredRoots: false }],
      "jsdoc/require-returns": ["error", { contexts: HELPERS_ONLY }],
      "jsdoc/check-param-names": "error",
      "jsdoc/check-tag-names": "error",
    },
  },
  // No spec imports another, so every binding in a spec is local to its file by
  // nature and the reason for documenting module scope does not reach it. A
  // fixture named `PASSWORD` or a `vi.mocked` alias gains nothing from a line
  // restating its name. Helpers still carry blocks, and the tag rules are
  // unchanged: a spec is where a stale @param hides best.
  {
    files: ["test/**/*.ts"],
    rules: {
      "jsdoc/require-jsdoc": ["error", { contexts: ["FunctionDeclaration", "ClassDeclaration"] }],
    },
  },
]);

export default eslintConfig;
