// Generated by Prisma, then extended for a dual-provider setup: SQLite by
// default, PostgreSQL when DATABASE_URL is a postgres:// URL. The provider line
// in schema.prisma is patched by scripts/resolve-provider.mjs; here we select
// the matching migration history. See scripts/db-provider.mjs.
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { detectProvider, MIGRATIONS_DIR } from "./scripts/db-provider.mjs";

const url = process.env["DATABASE_URL"];
// Provider-less commands (e.g. `generate` during a Docker build) may run with
// no DATABASE_URL set — fall back to the default SQLite engine there.
const provider = detectProvider(url, { fallback: "sqlite" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: MIGRATIONS_DIR[provider],
    // Lets `prisma db seed` (and the auto-seed after `prisma migrate reset`) run
    // the seed script. `npm run db:seed` invokes the same command directly.
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url,
  },
});
