import type { CategoryModel } from "@/generated/prisma-sqlite/models";

/** A category as it crosses to the client: plain, serialisable, no Prisma types. */
export interface CategoryDTO {
  /** Unique identifier, generated by the database. */
  id: string;
  /** Display name, unique across categories. */
  name: string;
  /** ISO 8601 timestamp of creation. */
  createdAt: string;
  /** Six-digit hex colour, used for the chip and the filter dot. */
  color: string;
}

/** Converts a category row into the shape a client can receive.
 *
 * @param model The category row as Prisma returns it.
 * @returns The same category, serialisable.
 */
export function toCategoryDTO(model: CategoryModel): CategoryDTO {
  return {
    id: model.id,
    name: model.name,
    createdAt: model.createdAt.toISOString(),
    color: model.color,
  };
}
