import type { TaskModel } from "@/generated/prisma-sqlite/models";

/** The states a task can be in.
 *
 * Stored as a String column rather than an enum, so one schema serves both
 * SQLite and Postgres.
 */
export type TaskStatus = "open" | "in_progress" | "closed";

/** A task as it crosses to the client: plain, serialisable, no Prisma types. */
export interface TaskDTO {
  /** Unique identifier, generated by the database. */
  id: string;
  /** Short summary the list and the dialog head with. */
  title: string;
  /** Markdown body, empty when the task has none. */
  description: string;
  /** Which of the three sections the task appears under. */
  status: TaskStatus;
  /** The category this task belongs to, or null when uncategorised. */
  categoryId: string | null;
  /** ISO 8601 timestamp of creation. */
  createdAt: string;
  /** ISO 8601 timestamp of the last change, which the list sorts on. */
  updatedAt: string;
}

/** Converts a task row into the shape a client can receive.
 *
 * Dates become ISO strings because a `Date` does not survive the boundary
 * between a Server Component and a Client one.
 *
 * @param model The task row as Prisma returns it.
 * @returns The same task, serialisable.
 */
export function toTaskDTO(model: TaskModel): TaskDTO {
  return {
    id: model.id,
    title: model.title,
    description: model.description,
    status: model.status as TaskStatus,
    categoryId: model.categoryId,
    createdAt: model.createdAt.toISOString(),
    updatedAt: model.updatedAt.toISOString(),
  };
}
